---
services:
  frontend:
    build:
      context: ./session2
    ports:
      - "5000:5000"
    environment:
      - BACKEND_URL=http://backend:5001
    depends_on:
      - backend

  backend:
    build:
      context: ./session2
    command: python backend.py
    ports:
      - "5001:5001"
    environment:
      - DB_HOST=mariadb
      - DB_USER=root
      - DB_PASSWORD=example
      - DB_NAME=testdb
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - ./db_data:/var/lib/mysql
